# helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n prometheus -f kube-prometheus-stack.yaml

kubeApiServer:
  enabled: false
kubelet:
  enabled: false 
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
alertmanager:
  enabled: false
grafana:
  enabled: true
  persistence:
    enabled: true

  grafana.ini:
    server:
      root_url: https://grafana.petersenandpetersen.com
      disable_login_form: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.petersenandpetersen.com
    tls:
      - hosts:
          - grafana.petersenandpetersen.com
        secretName: grafana.petersenandpetersen.com
    


prometheus:
  enabled: true
