apiVersion: v1
kind: Service
metadata:
  name: {{ include "holomatch.fullname" . }}
  labels:
    {{- include "holomatch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if and .Values.fullnameOverride (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: UDP
      name: http
  selector:
    {{- include "holomatch.selectorLabels" . | nindent 4 }}
